formatter: "markdown table"

content: |-
  # Example IAM Terraform Module

  {{ .Header }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Providers }}

  {{ .Requirements }}

  {{ .Resources }}

  {{ .Footer }}

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true